sudo: required
dist: trusty
language: python
python:
  - "3.4"
services:
  - docker
before_install:
  - echo "DATABASE_URL=postgresql://di_website:di_website_pw@db/di_website" > .env
  - docker volume create --name=diwebsite_db
  - docker-compose up --build -d
script:
  - docker-compose exec web python3 manage.py test
