sudo: required
dist: trusty
language: python
python:
  - "3.4"
services:
  - docker
before_install:
  - docker volume create --name=diwebsite_db
  - docker-compose up --build -d
script:
  - docker-compose exec web python3 manage.py test
