sudo: required
dist: trusty
language: python
python:
- '3.5'
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_5acf24e37bbb_key -iv $encrypted_5acf24e37bbb_iv -in deploy_key.enc -out deploy_key -d
- pip install codecov
- echo "DATABASE_URL=postgresql://di_website:di_website_pw@db/di_website" > .env
- docker volume create --name=diwebsite_db
- docker volume create --name="index_db"
- docker-compose up --build -d
script:
- docker-compose exec web /bin/sh -c "python3 -m coverage run manage.py test && python3 -m coverage xml && mv coverage.xml shared" && cd shared && python3 -m codecov
deploy:
 provider: script
 skip_cleanup: true
 script: cd .. && chmod 600 ./deploy_key && ssh -o StrictHostKeyChecking=no -i ./deploy_key AcceptEnv=EMAIL_BACKEND AcceptEnv=EMAIL_HOST AcceptEnv=EMAIL_HOST_USER AcceptEnv=EMAIL_HOST_PASSWORD di_website@178.128.102.213 ./deploy.sh
 on:
   branch: develop
