sudo: required
dist: trusty
language: python
python:
- '3.5'
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_29c27d68e731_key -iv $encrypted_29c27d68e731_iv
  -in deploy_key.enc -out ./deploy_key -d
- pip install codecov
- echo "DATABASE_URL=postgresql://di_website:di_website_pw@db/di_website" > .env
- docker volume create --name=diwebsite_db
- docker-compose up --build -d
script:
- docker-compose exec web /bin/sh -c "python3 -m coverage run manage.py test && python3
  -m coverage xml && mv coverage.xml shared" && cd shared && python3 -m codecov
