version: '2.2'

services:

  db:
    image: postgres:10
    environment:
      POSTGRES_DB: di_website
      POSTGRES_USER: di_website
      POSTGRES_PASSWORD: di_website_pw
    restart: always
    volumes:
      - diwebsite_db:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:6.2.4
    enviroment:
      discovery.type: single-node
      - ELASTIC_SEARCH_URL    
    ports:
      - "9200:9200"
      - "9300:9300"

  web:
    depends_on:
      - db
    expose:
      - "8090"
    env_file: .env
    environment:
        - HS_API_KEY
        - HS_TICKET_PIPELINE
        - HS_TICKET_PIPELINE_STAGE
    build:
      context: .
    volumes:
      - ./:/code/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  diwebsite_db:
    external: true
